name: Build

on:
  push:
    branches: [ legacy ]
  pull_request:
    branches: [ legacy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Build
        run: ./gradlew setupCiWorkspace && ./gradlew build
      - name: Rename
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*liquidbounce-b[0-9|.]*\.jar')
          export LB_VERSION=$(echo $JAR | sed -r 's/.\/liquidbounce-([a-zA-Z][0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION
          cp $JAR /home/runner/liquidbounce.jar
        

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: LB
          path: /home/runner/liquidbounce.jar
